function data = fx_readFluentDAT(fileName)

in     = importdata(fileName);
inVars = in.textdata;
d      = in.data;

% variable names in fluent, as present in the dat file header.
myStrings = {'x-coordinate',...
             'y-coordinate',...
             'z-coordinate',...
             'pressure',...
             'absolute-pressure',...
             'user-mass-source',...
             'y-plus',...
             'cell-volume',...
             'dynamic-pressure',...
             'velocity-magnitude',...
             'total-pressure',...
             'wall-shear',...
             'turb-kinetic-energy',...
             'density',...
             'x-wall-shear',...
             'y-wall-shear',...
             'z-wall-shear'};

% the names of our new variables in matlab. This must have the same order as "myStrings"
myVars    = {'x',...
             'y',...
             'z',... 
             'pst',...
             'pabs',...
             'mdot',...
             'yplus',...
             'Vcell',...
             'pdyn',...
             'Umag',...
             'ptot',...
             'tauw',...
             'tke',...
             'rho',...
             'tauwx',...
             'tauwy',...
             'tauwz'};
% myIdxs    = zeros([length(inVars),1]);

% Assign variables to our matlab data variable
for ii = 1:length(inVars)
    for jj = 1:length(myStrings)
        my_idx = strcmp(strtrim(inVars{ii}),myStrings{jj});
        
        if my_idx == 1
            %myIdxs(ii) = jj;
            myEval = sprintf('data.%s = d(:,%d);',myVars{jj},ii);
            eval(myEval);
        end
    end
end

end
